name: fast_tdl
services:
    tdl:
        container_name: tdl
        ports:
            - 8022:22
        volumes:
            - /Users/zen/.tdl:/root/.tdl
            - /Volumes/exchange/tdl:/data
        environment:
            - TDL=/data
            - PROXY=http://192.168.1.23:8889
            - MYSQL="192.168.1.9:3306"
        image: zhangyiming748/tdl:latest
