name: fast_tdl
services:
    tdl:
        container_name: tdl
        ports:
            - 8022:22
        volumes:
            - C:\Users\zen\.tdl:/root/.tdl
            - C:\Users\zen\Github\FastTdl:/data
        environment:
            - TDL=/data
            - PROXY=http://192.168.1.35:8889
        image: zhangyiming748/tdl:latest
