name: fast_tdl
services:
    tdl:
        container_name: tdl
        ports:
            - 8022:22
        volumes:
            - /Users/zen/.tdl:/root/.tdl
            - /Users/zen/github/FastTdl:/data
        environment:
            - TDL=/data
            - PROXY=http://192.168.1.18:8889
            - MYSQL_HOST=192.168.1.18
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASS=163453
        image: zhangyiming748/tdl:latest
