name: fast_tdl
services:
    tdl:
        container_name: tdl
        ports:
            - 8022:22
        volumes:
            - /Users/zen/.tdl:/root/.tdl
            - /Volumes/exchange/tdl:/data
        environment:
            - TDL=/data
            - PROXY=http://172.17.0.1:8889
            - MYSQL="172.17.0.1:3306"
        image: zhangyiming748/tdl:latest
