name: fast_tdl
services:
    tdl:
        container_name: tdl
        ports:
            - 8022:22
        volumes:
            - /path/to/.tdl:/root/.tdl
            - /path/to/FastTdl:/data
        environment:
            - TDL=/data
            - PROXY=http://192.168.1.31:8889
        image: zhangyiming748/tdl:v0.0.7