name: ffmpeg
services:
    golang:
        volumes:
            - /Users/zen/Downloads/media:/data
            - /Users/zen/github/FastTdl:/app
        container_name: ffmpeg
        working_dir: /app
        stdin_open: true
        tty: true
        image: golang:1.24.0-alpine3.21
        command: ash
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G